insert into MappingDB.dbo.F22
select *
from (select A.F2201,
             A.F2202,
             cast(concat(Format(A.F2203_M, 'yyyy/MM/dd'), ' ', SUBSTRING(A.F2204, 1, 2), ':',
                         SUBSTRING(A.F2204, 3, 2)) as datetime)                                as F2203,
             cast(concat(Format(A.F2205_M, 'yyyy/MM/dd'), ' ', SUBSTRING(A.F2206, 1, 2), ':',
                         SUBSTRING(A.F2206, 3, 2)) as datetime)                                as F2205,
             IIF(A.F2208 != '', cast(concat(Format(A.F2207_M, 'yyyy/MM/dd'), ' ', SUBSTRING(A.F2208, 1, 2), ':',
                                            SUBSTRING(A.F2208, 3, 2)) as datetime), null)      as F2207,
             A.F2209,
             A.F2210,
             A.F2211,
             A.F2212,
             A.F2213,
             A.F2214,
             A.F2215,
             A.F2216,
             A.F2217,
             A.F2218,
             A.F2219,
             A.F2220,
             A.nahi,
             A.Prv_St,
             A.Next_St,
             A.Is_Emdad,
             A.Emdad_Status,
             A.Len_Km,
             A.Invalid_Access_4_Block,
             A.Rec_Id,
             A.Rec_Id_InServer,
             A.AddLog_User,
             cast(concat(Format(A.addlog_Date, 'yyyy/MM/dd'), ' ', A.AddLog_Time) as datetime) as AddLog_Date,
             A.AddLog_IP,
             A.EditLog_User,
             A.Modify_Date                                                                     as EditLog_Date,
             A.EditLog_IP,
             A.Move_Counter,
             A.StopTime1,
             A.StopTime2,
             A.StopTime3,
             A.F15Rec_ID,
             A.F24Rec_Id
      from [172.23.27.208].Nafis_Seir_Proj.dbo.F22 as A
               Left join MappingDB.dbo.F22 as B on B.Rec_ID = A.Rec_ID
      where A.AddLog_Date > getdate() - 1
        and B.Rec_ID is null) as v
where v.AddLog_Date >= getdate() - 0.011;

update MappingDB.dbo.F22
set F2201                  = c.F2201,
    F2202                  = c.F2202,
    F2203                  = c.F2203,
    F2205                  = c.F2205,
    F2207                  = c.F2207,
    F2209                  = c.F2209,
    F2210                  = c.F2210,
    F2211                  = c.F2211,
    F2212                  = c.F2212,
    F2213                  = c.F2213,
    F2214                  = c.F2214,
    F2215                  = c.F2215,
    F2216                  = c.F2216,
    F2217                  = c.F2217,
    F2218                  = c.F2218,
    F2219                  = c.F2219,
    F2220                  = c.F2220,
    nahi                   = c.nahi,
    Prv_St                 = c.Prv_St,
    Next_St                = c.Next_St,
    Is_Emdad               = c.Is_Emdad,
    Emdad_Status           = c.Emdad_Status,
    Len_Km                 = c.Len_Km,
    Invalid_Access_4_Block = c.Invalid_Access_4_Block,
    Rec_Id                 = c.Rec_Id,
    Rec_Id_InServer        = c.Rec_Id_InServer,
    AddLog_User            = c.AddLog_User,
    AddLog_Date            = c.AddLog_Date,
    AddLog_IP              = c.AddLog_IP,
    EditLog_User           = c.EditLog_User,
    EditLog_Date           = c.EditLog_Date,
    EditLog_IP             = c.EditLog_IP,
    Move_Counter           = c.Move_Counter,
    StopTime1              = c.StopTime1,
    StopTime2              = c.StopTime2,
    StopTime3              = c.StopTime3,
    F15Rec_ID              = c.F15Rec_ID,
    F24Rec_Id              = c.F24Rec_Id
from MappingDB.dbo.F22 as d
         inner join (select *
                     from (select A.F2201,
                                  A.F2202,
                                  cast(concat(Format(A.F2203_M, 'yyyy/MM/dd'), ' ', SUBSTRING(A.F2204, 1, 2), ':',
                                              SUBSTRING(A.F2204, 3, 2)) as datetime)                                as F2203,
                                  cast(concat(Format(A.F2205_M, 'yyyy/MM/dd'), ' ', SUBSTRING(A.F2206, 1, 2), ':',
                                              SUBSTRING(A.F2206, 3, 2)) as datetime)                                as F2205,
                                  IIF(A.F2208 != '',
                                      cast(concat(Format(A.F2207_M, 'yyyy/MM/dd'), ' ', SUBSTRING(A.F2208, 1, 2), ':',
                                                  SUBSTRING(A.F2208, 3, 2)) as datetime),
                                      null)                                                                         as F2207,
                                  A.F2209,
                                  A.F2210,
                                  A.F2211,
                                  A.F2212,
                                  A.F2213,
                                  A.F2214,
                                  A.F2215,
                                  A.F2216,
                                  A.F2217,
                                  A.F2218,
                                  A.F2219,
                                  A.F2220,
                                  A.nahi,
                                  A.Prv_St,
                                  A.Next_St,
                                  A.Is_Emdad,
                                  A.Emdad_Status,
                                  A.Len_Km,
                                  A.Invalid_Access_4_Block,
                                  A.Rec_Id,
                                  A.Rec_Id_InServer,
                                  A.AddLog_User,
                                  cast(concat(Format(A.addlog_Date, 'yyyy/MM/dd'), ' ', A.AddLog_Time) as datetime) as AddLog_Date,
                                  A.AddLog_IP,
                                  A.EditLog_User,
                                  A.Modify_Date                                                                     as EditLog_Date,
                                  A.EditLog_IP,
                                  A.Move_Counter,
                                  A.StopTime1,
                                  A.StopTime2,
                                  A.StopTime3,
                                  A.F15Rec_ID,
                                  A.F24Rec_Id
                           from [172.23.27.208].Nafis_Seir_Proj.dbo.F22 as A
                           where A.AddLog_Date > getdate() - 10) as v
                     where v.AddLog_Date > getdate() - 10) as c
                    on c.Rec_ID = d.Rec_ID and c.EditLog_Date <> d.EditLog_Date;

select *
from MappingDB.dbo.F22
where AddLog_Date > getdate() - 0.011