SELECT [NO_VAG_]
      ,[Barnameh_ID]
      ,[BARDATE_]
      ,[AddLog_Time]
      ,[NOKALA_]
      ,[Disc1]
      ,[mabda_Code]
      ,[mabda_Disc]
      ,[Seir_mabda_Code]
      ,[Maghsd_Code]
      ,[Maghsd_Disc]
      ,[Seir_Maghsad_Code]
      ,[VAZN_C_]
      ,[VAZN_R_]
  FROM [172.23.27.214].[Bar].[dbo].[V_Bar_4_Trafik] where [BARDATE_] =14000817
GO